# Generated by Django 5.1.1 on 2024-09-26 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_alter_blog_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
